### ISSUE TITLE
Records lost in test.lobid.org

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1646] opened 2023-03-07 11:03 UTC
We observed today that in test.lobid.org nearly 400k records are missing. What happened?

**Comment by dr0i** [comment] 2023-03-07 11:23
You should use http://alma.lobid.org/ not test.lobid.org.

**Comment by hagbeck** [comment] 2023-03-07 11:36
We use "test" for our test system. But since die "Alma-FIX" is deployt, it could be better to switch back to "alma".

**Comment by dr0i** [comment] 2023-03-07 12:52
Ah, that is good to know - so your production service is not affected :)
 test.lobid.org is our alma-test server, so if you/we want to test something we can use that.
The discrepance of records on `test`  is not clear yet, so I leave the issue open.

**Comment by hagbeck** [comment] 2023-03-08 07:10
The records are now lost in alma.lobid.org, too. Cologne, we have a problem ;-)

**Comment by TobiasNx** [comment] 2023-03-08 08:36
Due to changes on and of the servers:
For test.lobid  the NZ fulldump was indexed on monday so that the new index was available yesterday.

For alma.lobid the NZ fulldump should have been fully indexed yesterday and the changes would have been available today. 
I guess that the missing 400.000 records are connected to the findexing of the fulldump or the last changes to the transformation.

@dr0i should know what this is about.
also perhaps @blackwinter knows if there are 400.000 records missing in the nz fulldump comparing to last week.

**Comment by dr0i** [comment] 2023-03-09 07:56
http://alma.lobid.org/resources/search?q=* reveals 25,651,775 hits. Index used: `resources-alma-fix-20230304-0829`
http://test.alma.lobid.org/resources/search?q=* exactly the same.  Index used: `resources-alma-fix-20230307-1248`

Note that the index of `alma.lobid.org` was build at Saturday and that index was ok as this issue was opened.
Would be good to know @hagbeck exact query to understand what is wrong.

**Comment by dr0i** [comment] 2023-03-09 08:26
Uhm, @TobiasNx made a aware that I the test index is not http://test.alma.lobid.org but  http://test.lobid.org .
And this test index differs indeed:
http://test.lobid.org/resources/search?q=* reveals 25,010,026.   This is to be investigated.

> The records are now lost in alma.lobid.org, too.

this I can't reproduce.

**Comment by dr0i** [comment] 2023-03-09 10:14
The discrepancy must be due to the indexing of RPB into the index `resources-alma-fix`. It should not affect @hagbeck  - i.e. your documents are unaffected by this. Can you confirm?

**Comment by hagbeck** [comment] 2023-03-09 10:41
We request our data with http://alma.lobid.org/resources/search?q=*&owner=DE-290&format=bulk. Is it possible, that some of our records are not bind to DE-290?

**Comment by hagbeck** [comment] 2023-03-09 11:13
Hm, it seems that since a few days our plausibility test works strange. The data from lobid is complete and seems correct. I've to debug our process.

Sorry for the circumstances!

**Comment by dr0i** [comment] 2023-03-09 12:55
Ok, that's fine then :)
Closing.

**Closed by dr0i** 2023-03-09 12:55 UTC
Labels: ALMA
