### ISSUE TITLE
Missing contributors without GNDId in mix with contributors with GNDId

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#507] opened 2017-07-06 09:52 UTC
Seems that MAB 108 and MAB 113 from
http://lobid.org/hbz01/HT018703339
are not transferred to the contribution array
http://lobid.org/resources/HT018703339.json
For comparison lobid v1 
http://lobid.org/resource/HT018703339/about

**Comment by ChristophEwertowski** [comment] 2017-09-06 13:57
The problem is that contributors with a GNDId are preferred to contributors without (https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L1348-L1352).

**Comment by jschnasse** [comment] 2017-09-06 14:33
I also found a working case. https://lobid.org/resources/HT019389958 provides a mixed contribution array.

**Comment by ChristophEwertowski** [comment] 2017-09-06 15:02
Like I supposed the contributors without the GNDId fall into `@contributorPersonLabel` and therefore are put into the json. Probably that's the reason why it took so long to find out about the missing contributors.

**Comment by jschnasse** [comment] 2017-10-09 11:05
Seems there is another case https://lobid.org/resources/HT019467953 . The author in MAB 108 is not contained in the contribution array.

**Comment by jschnasse** [comment] 2017-10-18 09:18
Hi Friends,

another case
- http://lobid.org/hbz01/HT019475982 with 14 creators
- https://lobid.org/resources/HT019475982 with no creator

Best
Jan

**Comment by dr0i** [comment] 2017-12-14 08:10
Deployed to staging, see http://lobid.org/resources/HT018703339.json , https://stage.lobid.org/resources/HT019467953.json and https://stage.lobid.org/resources/HT019475982.json.
@jschnasse please have a look.

**Comment by dr0i** [comment] 2017-12-14 08:37
Oh, running the play tests just discovered some rare probs with the labels subtsituted by an ID , see e.g. https://stage.lobid.org/resources/HT003654516.json .

**Comment by dr0i** [comment] 2017-12-18 08:06
Now evrything is good, right @jschnasse ?

**Comment by jschnasse** [comment] 2017-12-18 08:17
https://stage.lobid.org/resources/HT019475982 looks fine!
+1

**Comment by acka47** [comment] 2017-12-18 09:07
+1 from me as well. :tada:

**Comment by ChristophEwertowski** [comment] 2018-01-02 13:12
Apparently while merging the order was lost again. See http://lobid.org/resources/HT019475982.json.

**Comment by ChristophEwertowski** [comment] 2018-01-11 09:51
Order fixed in https://github.com/hbz/lobid-resources/pull/662. Closing this issue.

**Closed by ChristophEwertowski** 2018-01-11 09:51 UTC
Labels: bug
