### ISSUE TITLE
Missing resource HT019401017

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#537] opened 2017-07-31 07:54 UTC
in both indexes

**Comment by ChristophEwertowski** [comment] 2017-08-01 08:08
Can't be found in hbz01 either but is in the old catalogue. The only conspicuous thing I see is that the GND-Id in 078r is not in subfield 9 like the other GND-Ids.

**Comment by ChristophEwertowski** [comment] 2017-08-03 12:13
@aquast told me that multiple resources are missing. First guess: Transformation from union catalog to hbz01 didn't work.

**Comment by aquast** [comment] 2017-08-03 12:20
HT019404829
HT019404808
HT019404913

these resources are missing recently

**Comment by aquast** [comment] 2017-08-03 12:30
all these resources are where first time catalogued at 31-07-2017

**Comment by fsteeg** [comment] 2017-08-07 12:17
Got the missing updates since 2017-07-27 from Aleph and indexed in API 1, hbz01, and API 2:

http://lobid.org/resource/HT019401017
http://lobid.org/resource/HT019404829
http://lobid.org/resource/HT019404808
http://lobid.org/resource/HT019404913

http://lobid.org/hbz01/HT019401017
http://lobid.org/hbz01/HT019404829
http://lobid.org/hbz01/HT019404808
http://lobid.org/hbz01/HT019404913

http://lobid.org/resources/HT019401017
http://lobid.org/resources/HT019404829
http://lobid.org/resources/HT019404808
http://lobid.org/resources/HT019404913

Investigating root cause and required fixes for future updates and baselines.

**Comment by fsteeg** [comment] 2017-08-08 10:52
Opened https://github.com/hbz/lobid-resources/issues/541 for restoring automatic updates.

Missing resources are restored in production, see https://github.com/hbz/lobid-resources/issues/537#issuecomment-320648062, closing.

**Closed by fsteeg** 2017-08-08 10:52 UTC
Labels: bug, review
