### ISSUE TITLE
Unthrottled search requests result in errors

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#572] opened 2017-09-28 11:35 UTC
After about 4000 unthrottled search requests the API starts returning errors.

Will set up a scenario for reproduction and add intructions here.

**Comment by fsteeg** [comment] 2017-09-28 12:23
To reproduce, get NWBib, checkout `392-wikidata`, `run` and visit: 

http://localhost:9000/classification?t=Wikidata

Errors start at some point after request 4000 (see log).

This uses http://stage.lobid.org/resources with changes from `572-errors`.

**Comment by fsteeg** [comment] 2017-09-28 12:40
Sorry, forgot to mention the crucial step to actually get the errors: disable the client side throttling by commenting out this line: https://github.com/hbz/nwbib/blob/392-wikidata/app/controllers/nwbib/WikidataLocations.java#L115

**Comment by dr0i** [comment] 2017-10-06 09:30
I got now error, although outcommented the sleep. Using VPN 4500 requests take 12m. Can imagine that that is slow enough in itself. Going to use it directly on our es-server.

**Comment by dr0i** [comment] 2017-10-06 11:14
Omitting VPN and use a direct external connection indeed quickens the querying by factor 2 ( so now takes 6m ) but is without error, too. So the step to reproduce seems to be to start the web-app as near to the index as possible.

**Comment by dr0i** [comment] 2017-10-09 15:36
Running on the same server the *Request* is again faster,  now it takes ~1m for 1k. And the `error` now indeed occurs. Web-app logs: 

> Could not query index: None of the configured nodes are available: [{#transport#-1}{193.30.112.84}{aither.hbz-nrw.de/193.30.112.84:9300}, {#transport#-2}{193.30.112.82}{gaia.hbz-nrw.de/193.30.112.82:9300}]

Since the `java` versions where slightly different I synced them. Also a `memlock=unlimited` was not configured on aither. Updated all, made sure it's in sync, restarted. Errors again. My suspicion now: `es` must also be restarted on gaia (which I didn't do because it may be hardwired into webapps). Will try this tomorrow.

**Comment by dr0i** [comment] 2017-10-10 11:08
Restarted `es@gaia` to no avail. As throttling is a workaround this has to suffice at the moment. Posponing this issue.

**Comment by dr0i** [comment] 2017-10-30 10:52
We got too much of the `None of the configured nodes are available:` errors to ignore them. I wasn't able to track this down - network seems to be ok. So maybe it is the mix of `Client`  and `TransportClient`. Haven't figured that out yet, and there are some ES-patches regarding this. I propose to switch to:
1. newest ES
2. weywot[34] as new cluster
and see how things fugured out. What do you think @fsteeg ?

**Comment by fsteeg** [comment] 2017-10-30 13:24
As discussed offline, I agree that moving to a new ES would be great, but it would cause some work due to API changes in the lobid-resources and mabxml-elasticsearch repos, which access our ES cluster.

**Comment by dr0i** [comment] 2017-12-29 13:18
Tested against the new weywot-ES-5.6.3-cluster: great !
8k lookups in 1.5m (testing on weywot2). No errors :)
Load on cluster <1.0 .
I think this issue is finally gone.
Going to undo throttling.

**Comment by dr0i** [comment] 2018-01-02 08:48
Deployed to master, closing.

**Closed by dr0i** 2018-01-02 08:48 UTC
Labels: deploy
