### ISSUE TITLE
Enable owner facets

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1618] opened 2023-01-30 16:11 UTC
We need (not as URIs, but as simple String-IDs ("plain Isil")):
- [x]  owner facets

At at an even later date (June or Juli):
 - [x]  owner facets of sub ISILs ("Institutionszugehörigkeit")
 
In Alma-Fix-lobid-resources we don't have an owner facet atm in the GUI - but the data provides ES-`aggs` so that one can use that to build a `facet`.
~~We need to enable URL-encoding so this depends on https://github.com/hbz/lobid-resources/issues/1521.~~
~~We need then to set `heldBy.sublocation` to have the owner.~~ ~~Depends on https://github.com/hbz/lobid-resources/issues/1602~~
@acka47  noted that it would be nice to be able to filter on cities.

**Comment by TobiasNx** [comment] 2023-03-10 12:11
@dr0i is this a duplicate to : #1602 

btw. missing url encoding of item-`id` is not blocking this anymore since the id-pattern changed: #https://github.com/hbz/lobid-resources/pull/1647

**Comment by acka47** [comment] 2023-03-10 13:29
Duplicate of #1602. Closing.

**Comment by acka47** [comment] 2023-03-13 11:37
Reopening

**Comment by TobiasNx** [comment] 2023-03-13 11:42
Isn't this query based on the owner facette: http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38%23%21&aggregations=owner

**Comment by dr0i** [comment] 2023-03-13 15:27
First question is: was this issue properly named? @blackwinter do you need the GUI enabled to show owner facets or di you need ES-`aggs`  to build your own facets- the latter is working like this:
```
curl -XGET  'http://$esServer:9200/resources/_search?q=linux&pretty=true' -d '
{
  "aggs": {
            "top-isil": {
              "terms": {
                "field": "hasItem.heldBy.id",
                "size": 50
              }
            }
      }
}
'
```

**Comment by blackwinter** [comment] 2023-03-13 15:29
> do you need the GUI enabled to show owner facets or di you need ES-`aggs` to build your own facets

The latter. We don't care about Lobid GUI in this context.

**Comment by dr0i** [comment] 2023-03-14 08:49
@TobiasNx we need:
>  owner facets of sub ISILs ("Institutionszugehörigkeit")

We already have `hasItem.sublocation.id` (with values like e.g. `https://hbz-network.userservices.exlibrisgroup.com/view/uresolver/49HBZ_FUH
/openurl?u.ignore_date_coverage=true&rft.mms_id=99381842456506464` => no ISIL) but we need a  `hasItem.heldBy.sublocation.id`).
Or do we already have subIsils - we have:
`hasItem.heldBy.id`:http://lobid.org/organisations/DE-Hag4-2#! (see http://alma.lobid.org/resources/990223521400206441.json). It's not typed as `sublocation` though - is this even necessary @blackwinter ?

**Comment by TobiasNx** [comment] 2023-03-14 09:00
Here things get confused. 

`hasIten.heldby.id`
`hasIten.heldby.isil`

=> both provide the sublibrary ISIL If the library provides them. This is/was the task of : #1607 and #1652 

`sublocation` is a specific for e-resources which has nothing to do with sublibraries.

**Comment by dr0i** [comment] 2023-03-14 09:37
Thx @TobiasNx for further clarification. I would remove the issues' description "We need then the to set heldBy.sublocation to have the owner. " if I understand correctly. Also, we are done here and can close the issue @blackwinter ?

**Comment by TobiasNx** [comment] 2023-03-14 09:42
yes, `hasItem.heldBy.id` (lobid-org URI) and `hasIten.heldby.isil` (ISIL Nr.) provide the location of the sublibrary if provided. Yes please drop the task: "We need then to set heldBy.sublocation to have the owner.

**Comment by dr0i** [comment] 2023-03-14 09:45
Assigning @blackwinter for reviewing.

**Comment by TobiasNx** [comment] 2023-03-14 09:49
Notice that we build the lookup for the Wave 1 and Wave 2 Libraries at the moment: #1652

**Comment by blackwinter** [comment] 2023-03-14 10:45
> Also, we are done here and can close the issue @blackwinter ?

Sorry, I don't understand. What is done? I can't find an (aggregratable) `owner` field in the index mapping, nor `hasIten.heldby.isil`. What am I missing?

**Comment by dr0i** [comment] 2023-03-14 11:30
What do we need _exactly_ ? The `agg` mentioned in https://github.com/hbz/lobid-resources/issues/1618#issuecomment-1466364966 is obviously not sufficient. Why not? Do you need a plain field of `isil` instead of a URI? So enabling `hasItem.heldBy.isil` as `agg` we are done?

**Comment by blackwinter** [comment] 2023-03-14 11:34
> Do you need a plain field of `isil` instead of a URI? So enabling `hasItem.heldBy.isil` as `agg` we are done?

Yes, exactly, that's it.

**Comment by dr0i** [comment] 2023-03-20 08:23
#1661 seems to work:
```
curl -XGET  'http://$esServer:9200/resources/_search?q=linux&pretty=true' -d '
{
  "aggs": {
            "top-isil": {
              "terms": {
                "field": "hasItem.heldBy.isil",
                "size": 50
              }
            }
      }
}
'
```
=>
```
 },
  "aggregations" : {
    "isil" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 62,
      "buckets" : [
        {
          "key" : "DE-1044",
          "doc_count" : 2360
        },
        {
          "key" : "DE-465",
          "doc_count" : 2090
        },
```

**Comment by dr0i** [comment] 2023-03-20 08:25
Also sub ISILs exist:
```
    {
          "key" : "DE-Hag4-2",
          "doc_count" : 119
        },
        {
          "key" : "DE-Lan1",
          "doc_count" : 67
        },
        {
          "key" : "DE-Hag4-4",
          "doc_count" : 50
        },
        {
          "key" : "DE-Hag4-3",
          "doc_count" : 44
        },
        {
          "key" : "DE-1393-BOT",
          "doc_count" : 38
        },
        {
          "key" : "DE-6-022",
          "doc_count" : 37
        },
```

**Comment by blackwinter** [comment] 2023-03-20 10:58
:+1: Thank you.

**Closed** 2023-03-20 11:06 UTC
Labels: DigiBib
