### ISSUE TITLE
No results shown in UI

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#327] opened 2017-03-20 14:00 UTC
Currently the UI doesn't show results while the underlying JSON works. Example:

http://lobid.org/resources/search?q=k%C3%B6ln (no results to see)
http://lobid.org/resources/search?q=k%C3%B6ln&format=json (everything normal)

**Comment by fsteeg** [comment] 2017-03-21 08:24
As a first step, I rolled back production to the state before https://github.com/hbz/lobid-resources/pull/326, which caused the regression:

http://lobid.org/resources/search?q=k%C3%B6ln

**Comment by fsteeg** [comment] 2017-03-21 09:38
Deployed to stage:

http://stage.lobid.org/resources/search?q=k%C3%B6ln
http://stage.lobid.org/resources/TT050409948?format=json

**Comment by acka47** [comment] 2017-03-21 09:40
Seems to be already deployed to production. Nonetheless, +1.

**Comment by fsteeg** [comment] 2017-03-21 09:42
Production was rolled back, see https://github.com/hbz/lobid-resources/issues/327#issuecomment-288007273, does not contain #326, see:

http://lobid.org/resources/TT050409948?format=json

**Comment by ChristophEwertowski** [comment] 2017-03-21 10:41
+1 Because there is no code to review, I'm closing this issue.

**Comment by fsteeg** [comment] 2017-03-21 10:52
There is an associated code review: https://github.com/hbz/lobid-resources/pull/329

**Closed** 2017-03-21 12:55 UTC
Labels: bug, deploy
