### ISSUE TITLE
Samples not working in JSON-LD Playground

### ISSUE THREAD

**Issue by gregorbg** [hbz/lobid-resources#1317] opened 2021-12-04 10:48 UTC
Hello! Upon trying to examine the [default sample](https://lobid.org/resources/HT018472857?format=json) given on your [API documentation page](https://lobid.org/resources/api) by using the [JSON-LD playground](https://json-ld.org/playground/), I am confronted with the following error message:
```
jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain type
```

I have tried manually switching to either `JSON-LD 1.0` or `JSON-LD 1.1` parsing under `Option`; both fail with the same error. Here's a [permalink for reference](https://tinyurl.com/y5reerjg).

By contrast, both the samples from [lobid-gnd](https://lobid.org/gnd/4074335-4.json) and [lobid-organisations](https://lobid.org/organisations/DE-6?format=json) _can_ be parsed in JSON-LD playground without any problems. I suspect that something is wrong with the `context` schema at http://lobid.org/resources/context.jsonld, because its formatting looks substantially different from the schemas of [lobid-gnd](http://lobid.org/gnd/context.jsonld) and [lobid-organisations](http://lobid.org/organisations/context.jsonld). But this is just a hunch, I am not knowledgeable enough in JSON-LD to exactly put my finger on it.

Thanks for working on this project, I really appreciate that you're making all of the catalogue data openly available! :smiley:

**Comment by acka47** [comment] 2021-12-06 07:27
Thanks for the detailed bug report. This should be fixed with #1318. The problem is that we used [aliased keywords](https://www.w3.org/TR/json-ld/#aliasing-keywords) not only in the instance data but in the JSON-LD context itself which apparently does not work.

**Comment by acka47** [comment] 2021-12-06 07:33
@gregorbg I am curious about your use case for lobid. Let us know if you plan to use it in you daily workflows and/or encounter any problems. You can reach us via lobid-admin \[at\] hbz-nrw \[dot\] de or via the chat at https://chat.gwdg.de/channel/lobid.

**Comment by dr0i** [comment] 2021-12-06 08:28
It's not solved yet, see  #1318.

**Comment by gregorbg** [comment] 2021-12-07 14:23
Hey, thank you for the quick fixes! As far as I'm concerned it works now; I've sporadically tested a few random HT entries and they were all processed by the JSON-LD Playground without any error. :+1:

I'd love to talk and get in touch some more about using the lobid API, I'll join the chat or write an email when I get the chance later this week.

**Closed** 2021-12-09 08:49 UTC
Labels: bug

**Comment by dr0i** [comment] 2021-12-09 08:57
Thx again @gregorbg for the report. We appreciate that.
We are looking forward to your questions concerning the lobid API.
