### ISSUE TITLE
Rename "Inhaltsangabe"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#361] opened 2017-03-31 14:40 UTC
http://lobid.org/resources/search?q=publication.description:* gives the set of resources which have a description. This description is called "Inhaltsangabe" which isn't 100 percent right. Often it contains a subtype of the publication form like ["Digitalisierte Ausgabe"](http://lobid.org/resources/CT001006866) or ["Mikrofiche-Ausg.:"](http://lobid.org/resources/HT013157965). An "Inhaltsangabe" for me is a content summary of some sort. 
I don't know why there is a ```:``` in the MAB field 610. It's noted in the [badly catogued ticket](https://github.com/hbz/lobid-resources/issues/258).
With the superflous link is dealt with in #360.

**Comment by fsteeg** [comment] 2017-04-03 07:43
The issue is actually that the wrong JSON field is used, TOC used to be a `description` field in the JSON, but now it's `tableOfContents`.  The UI however still looks for a `description`, and finds it in the `publication` object. So this is covered by https://github.com/hbz/lobid-resources/issues/339, closing.

**Closed by fsteeg** 2017-04-03 07:43 UTC

**Comment by acka47** [comment] 2017-04-03 07:44
The remaining question is whether we want the information from `publication.description` shown somewhere in the UI or if it is ok to be left out...

**Comment by ChristophEwertowski** [comment] 2017-04-03 13:30
From my point of view the information can be left out. Users can conclude that an online resource from 1837 wasn't created then. I think it's not that important that it can be read that it is a digitalisation. 
The same for Microfiche resources. I think libraries who have microform resources normally have both microfilm and microfiche resources and readers. 

Other descriptions are a bit more complex. In the following the more complex examples of the first 30 hits:
* http://lobid.org/resources/HT013209275: The information that it is a microfilm resource on a microfilm roll isn't covered by other fields.
* http://lobid.org/resources/HT017844795, http://lobid.org/resources/TT001629704: All information is in other MAB fields, although not mapped to JSON.
* http://lobid.org/resources/HT013209432: The information that the resource consists of two microfiche in 48 magnification.

All in all most of the information of the more complex examples could be covered or are already covered. And of course, "hidden for normal users", it can be seen in the JSON.
