### ISSUE TITLE
Add link to related zdb resources

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#367] opened 2017-04-04 12:44 UTC
A customer from the ZBMed wants to have the ISSN from the fields 542 and 545 in the PUBLISSO repository. 542 is the standard ISSN field which is already implemented. 545 is used by the ZDB for paralel edition (e.g. an online version of a printed resource or the other way around). Since this relation is not coved elsewhere we should implement it.  

Jira issue: https://jira.hbz-nrw.de/browse/FRL-156

**Comment by ChristophEwertowski** [comment] 2018-03-01 09:45
I wasn't 100% correct. From the [BVB](https://www.bib-bvb.de/web/kkb-online/felder-540-580):
```
545 Weitere ISSN für fortlaufende Sammelwerke
545_ ISSN formal nicht geprüft
545a ISSN formal richtig
545b ISSN formal falsch  

Unterfeld:
a = Autorisierte ISSN
b = ISSN der Ausgabe auf Datenträger
c = ISSN der Internetausgabe
d = ISSN der Druckausgabe
```
@acka47: I propose to use MAB 545- and MAB 545a, as 545b could lead to confusion if a customer gets back a correct resource and an incorrect resource. I think we should also use the property `eissn` like @jschnasse does in edoweb.

**Comment by acka47** [comment] 2018-03-09 09:53
Frankly, I don't like the `issnOfParallelResource` approach very much. This is not very very linked-data-like to add information about another resource in a separate resource. I'd prefer adding lnks to the related ZDB resources. In the case of the example, we have a link to the print version in 527 we could use to create a  link to the resource where people can get the identifiers?

```xml
<datafield tag="527" ind1="z" ind2="1">
  <subfield code="p">Druckausg.</subfield>
  <subfield code="a">Physics of plasmas</subfield>
  <subfield code="9">HT006157459</subfield>
</datafield>
```

Furthermore, we have links we don't use yet to the electronic resources from the print resource, see http://lobid.org/hbz01/HT006157459:

```xml
<datafield tag="776" ind1="-" ind2="1">
  <subfield code="i">Online-Ausg.</subfield>
  <subfield code="t">Physics of plasmas</subfield>
  <subfield code="d">[S.l.] : American Institute of Physics, 1994-</subfield>
  <subfield code="h">Online-Ressource</subfield>
  <subfield code="9">HT010726584</subfield>
</datafield>
```
So, my suggestion is to close this isse and open another one that is about adding relations to ZDB resources.

BTW, the ZDB does a very good job in visualizing the relations of the resources, see e.g. http://zdb-katalog.de/title.xhtml?idn=019658389&tab=4.

**Comment by acka47** [comment] 2018-03-09 11:52
> my suggestion is to close this issue and open another one that is about adding relations to ZDB resources.

We might also just rename this issue to "Add links to related zdb resources"

**Comment by ChristophEwertowski** [comment] 2018-03-09 12:38
Since it's a similar topic I just renamed the issue. This way we also have the history of it in one issue.

**Comment by ChristophEwertowski** [comment] 2018-03-14 13:48
Deployed to test. See `otherEditionOfResources` at [HT010726584 (test, json)](http://test.lobid.org/resources/HT010726584.json) for MAB 527 (RAK). For MAB 775 and 776 (RDA fields) see [HT002192569 (test, json)](http://test.lobid.org/resources/HT002192569.json). `Frankfurter Allgemeine / R. R, Rhein-Main-Zeitung` is the example of MAB 775 for which I changed the MAB-XML-test file (look in hbz01XmlClobs for the changed file not at hbz01).

**Comment by acka47** [comment] 2018-03-15 14:36
The problem is that information like "Online-Ausg." strictly speaking is not about the other edition but about the relation between the described resource and the parallel resource. Thus, we should also handle it like this in the RDF. There are three options:

1. Leave the information out and just link to the other edition (like ZDB does in its RDF)
2. Add a level of indirection, i.e. a bnode for the relation where we can put the information.
3. Use different properties for each relation.

As discussed offline, we will check what different values for the type of parallel edition ("CD-ROM-Ausg.", "Druckausg." etc.) there are. If the number is not too big we might use/create separate properties for the different relations.

**Comment by ChristophEwertowski** [comment] 2018-03-15 15:30
Examples from the Feldhilfe about MAB 775:
```
Beispiele:

         Parallele Sprachausgabe:
         775  $i Parallele Sprachausgabe  $n französisch  $a Organisation for Economics Cooperation and Development
                  $t Statistiques de l'OCDE sur les assurances  $x 2226-5805  $9 HT…

         Titel ist auch in einer Reihe erschienen:
         775  $i Äquivalent  $k Pichlers Jugendbücherei ; 82-84

         Beziehung zwischen zwei Manifestationen, die als Aufsatz und auch allein veröffentlicht wurden:
         775  $i Äquivalent  $a Beyerle, Gert  $t Zusammenhang zwischen Personalbedarf und Dienstplantechnik
                  $n Enthalten in: Verwaltungsführung, Organisation, Personal. - 1985, September/Oktober. - Seiten 251-254  $x 0170-7140
                  $9 HT
```
So for MAB 775 we could stick to information like "Parallelausg." or use the information of MAB 050 as the linked resource from MAB 775 should have the same medium.

**Comment by ChristophEwertowski** [comment] 2018-03-15 15:38
Examples from the Feldhilfe about MAB 527:
```
527z  $p Übersetzung von
                   $a The photographic card deck of the elements / Theodore Gray
                   $9 hbz-IDN

527z  $p Parallele Sprachausgabe $n englisch
                   $a Annual report / Landesbank Berlin Holding
                   $9 hbz-IDN

527z  $p Erscheint auch als
                   $n Druck-Ausgabe
                   $a Internationales Jahrbuch für Medienphilosophie
                   $9 hbz-IDN
```
As you can see, this field can contain examples like in MAB 775 (first two examples) and MAB 776 (last example).

**Comment by ChristophEwertowski** [comment] 2018-03-15 17:26
I created a statistic.

MAB 527?1.p (406.815 resources): At least 137.600 resources contain the string "Druckausg.", at least 84.100 the string "Online-Ausg.", at least 31.200 "Internetausg." or "Internet-Ausg.", at least 28.000 the string "Digital. Ausg.", at least 20.200 "Parallelausg." and 10.600 "CD-ROM-Ausg.". The rest contains mostly out of language descriptions.
MAB 776-1.i (114.736 resources): 81.474 resources contain the string "Erscheint auch als", 24.567 resources "Druckausg.", 11.450 "Online-Ausg.".
MAB 776-1.n (70.103 resources): At least 28.400 resources contain the string "Druck-Ausgabe", at least 39.600 resources the string "Online-Ausgabe".
MAB 527?1.n (24.174 resources): At least 11.400 resources contain the string "Druck-Ausgabe", 9.800 the string "Online-Ausgabe". The rest of the entries don't appear that often.
MAB 775-1.i (2.592 resources): Here strings like "Parallele Sprachausgabe", "Parallelausgabe" or "Übersetzung" can be found.

**Comment by ChristophEwertowski** [comment] 2018-03-21 12:36
Deployed to test. See [HT002192569 (test, json)](http://test.lobid.org/resources/HT002192569.json) where I created four properties: `dataCarrierVersionOfResources`, `printVersionOfResource`, `onlineVersionOfResource` and `otherVersionOfResource`. As I talked with fsteeg about it, he proposed to take a property for all editions of a resource like your second proposal.

**Comment by acka47** [comment] 2018-03-22 09:35
Discussing this offline, we decided to only use a simple relation property like the ZDB. For more information on the relation, the linked resource has to be checked (e.g. is it an onlijne or print resource, what's its ISSN etc.).

**Comment by ChristophEwertowski** [comment] 2018-03-22 13:51
Deployed to test. See [HT002192569 (test, json)](http://test.lobid.org/resources/HT002192569.json).

**Comment by acka47** [comment] 2018-03-22 16:15
I'd prefer "related" as label. Otherwise +1.

**Closed** 2018-03-27 11:40 UTC
Labels: deploy
