### ISSUE TITLE
Values of 'type' field should be strings, not objects

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#27] opened 2016-02-15 09:27 UTC
Compare API 1.x http://lobid.org/resource/BT000168595/about?format=full

```
"@type": [
    "http://purl.org/dc/terms/BibliographicResource",
    "http://purl.org/ontology/bibo/Book"
]
```

And data 2.0 http://gaia.hbz-nrw.de:9200/resources/resource/BT000168595/_source

```
"type": [
    {
        "@id": "http://purl.org/dc/terms/BibliographicResource"
    },
    {
        "@id": "http://purl.org/ontology/bibo/Book"
    }
]
```

**Edit**: Same for `medium`, `nwbibspatial`, `nwbibsubject`, `collectedBy`, `isPrimaryTopicOf`,  `sameAs`

**Comment by dr0i** [comment] 2016-02-15 09:30
Not sure about this. Seems to be corect in API 2.0, because http URIs _are_ IDs, no? But I remember somehow to get rif of the @id, yes? Asking @acka47 .

**Comment by fsteeg** [comment] 2016-02-15 09:53
Same for `medium`, `nwbibspatial`, `nwbibsubject`, `collectedBy`, `isPrimaryTopicOf`, and `sameAs`.

Again compare:

http://lobid.org/resource/BT000168595/about?format=full
http://gaia.hbz-nrw.de:9200/resources/resource/BT000168595/_source

Also adding this to the issue description.

**Comment by fsteeg** [comment] 2016-02-15 09:55
@dr0i @acka47 As far as I remember it's a simple context setting.

**Comment by acka47** [comment] 2016-02-15 10:00
I'd say, this is a duplicate to https://github.com/hbz/lobid-rdf-to-json/issues/26.

**Comment by acka47** [comment] 2016-02-15 10:35
> Same for `medium`, `nwbibspatial`, `nwbibsubject`, `collectedBy`, `isPrimaryTopicOf`, and `sameAs`.

This might make sense for some – especially `medium`. I was curious whether it actually is possible to map URIs to strings in the `@context` for other cases than JSOn terms (properties) or values of the `@type` keyword. It looks like it is NOT possible. See the sentence in the [spec, 5.4](http://www.w3.org/TR/json-ld/#specifying-the-type):

> The value of an @type key may also be a term defined in the active context

This implies that it is not possible for other URIs which is confirmed by the JSON-LD playground, see e.g. http://tinyurl.com/zoxpsqs.

Thus, we won't have to discuss this more and should rather discuss @jschnasse's "side car" proposal of adding a `prefLabel` statement to `@id` statements, e.g.:

```javascript
{
  "@id": "http://lobid.org/resources/HT12345",
  "@type": [ 
    {
      "@id": "http://purl.org/dc/terms/BibliographicResource",
      "prefLabel": "Bibliographic Resource"
    },
    {
      "@id": "http://purl.org/ontology/bibo/Book",
      "prefLabel": "Book"
    }
  ]
}
```

**Comment by fsteeg** [comment] 2016-02-15 11:37
@acka I'm a bit confused. This issue and the part you quoted:

> Same for `medium`, `nwbibspatial`, `nwbibsubject`, `collectedBy`, `isPrimaryTopicOf`, `sameAs`.

Is about them being objects, not strings. They should be strings like in the current API.

What you write sounds more about aliasing. Or am I getting something wrong?

**Comment by acka47** [comment] 2016-02-15 12:05
> Is about them being objects, not strings. They should be strings like in the current API.

> What you write sounds more about aliasing. Or am I getting something wrong?

Oups, you are right. Nonetheless, these are related. If we use the "side car" approach, we will need objects...

**Comment by acka47** [comment] 2016-02-15 13:01
Regarding the original issue: As the `@contextalready contains the information `"@type" = "@id"` for the respective terms, the object with `@id` shouldn't be used in the actual data. See this example in the playground: http://tinyurl.com/hfbvakd

**Comment by acka47** [comment] 2016-02-15 13:06
Closing this one as it is worked on this within https://github.com/hbz/lobid-rdf-to-json/issues/28. The terms for `@types` thing is discussed in https://github.com/hbz/lobid-rdf-to-json/issues/26. The side-car approach will be discussed in a meeting on Thursday.

**Closed by acka47** 2016-02-15 13:06 UTC
Labels: nwbib-launch, ready
