### ISSUE TITLE
Replace Bibframe 1.0 URIs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#164] opened 2017-01-13 12:30 UTC
The namespace for the current Bibframe model (2.0) differs from the first Bibframe vocabulary publication (1.0). Thus, we will have to update our URIs. We have four entries in the context from the old namespace (bibframe.og):

- http://bibframe.org/vocab/contribution --> http://id.loc.gov/ontologies/bibframe/contribution
- http://bibframe.org/vocab/relator --> already covered by #142
- http://bibframe.org/vocab/agent --> http://id.loc.gov/ontologies/bibframe/agent
- http://bibframe.org/vocab/Contribution --> http://id.loc.gov/ontologies/bibframe/Contribution

**Comment by ChristophEwertowski** [comment] 2017-01-18 08:58
Duplicate of #164 . Closing

**Comment by dr0i** [comment] 2017-01-19 14:15
Since the data is not yet indexed the branch shouldn't be merged. Reverted that merge.

**Closed** 2017-01-23 09:07 UTC
Labels: API 2.0, deploy
