### ISSUE TITLE
Remove link from "Inhaltsangabe"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#360] opened 2017-03-31 14:20 UTC
http://lobid.org/resources/search?q=publication.description:* leads to a list of all resources with a description which is then transformed into a link. These links lead to nothing.

**Comment by fsteeg** [comment] 2017-04-03 07:37
Duplicate of https://github.com/hbz/lobid-resources/issues/339, closing.

**Closed by fsteeg** 2017-04-03 07:37 UTC
Labels: bug, ready
