### ISSUE TITLE
Error in "inCollection"

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1125] opened 2021-02-18 13:04 UTC
We have a problem with records of the collection "ZDB-23-DGG-eba". In lobid-resources there only is

```
'inCollection' | 'id' | "http://lobid.org/organisations/ZDB-23-DGG#!"
```

In the corresponding MAB-XML record it is correct:

```
<datafield tag="078" ind1="e" ind2="1">
<subfield code="a">ZDB-23-DGG-eba</subfield>
</datafield>
```

Example: http://lobid.org/resources/HT020719239.json

**Comment by dr0i** [comment] 2021-02-19 12:09
Fix in master. Data should be fixed after full reindexing at Sunday. To be checked then.

**Comment by TobiasNx** [comment] 2021-02-22 07:48
The new regex also needs to be integrated in the AMLA-Morph, since inCollection there was rebuild from the ALEPH-Workflow. Should I do that in this branch? Or open up a new one?

**Comment by dr0i** [comment] 2021-02-22 07:56
Reuse this issue, as it fits to both databases.
Also I propose to not tag this issue with `almaMigration` but leave it as it is, for the issue is not alma specific.

**Comment by TobiasNx** [comment] 2021-02-22 08:15
I have locally updated the ALMA-Moprh but I need a new ALMA testfile. Where do i get the ALMA-MARC of http://lobid.org/resources/HT020719239.json

**Comment by dr0i** [comment] 2021-02-22 08:37
Look at https://github.com/hbz/lobid-resources/issues/1110. It's possible to get the source but you have to know the `almaMmmsId`. Don't know if this is sufficient for you, we would have to open an issue of itself if not.

**Comment by dr0i** [comment] 2021-02-22 11:15
>  It's possible to get the source but you have to know the almaMmmsId.

Uh, no , we are good: 

https://indexes.devel.digibib.net/export/HT017664407

will give you an link to get the resource by `almaMmsId`. \o/

**Comment by dr0i** [comment] 2021-02-22 14:33
@hagbeck we fixed it for lobid-resources (aleph),  look e.g. at http://lobid.org/resources/HT020719239.json . Now have to fix alma data accordingly.
Thx for the report !

**Comment by dr0i** [comment] 2021-02-26 14:46
Fixed for both ETLs: Alma and Aleph.
Closing.

**Closed by dr0i** 2021-02-26 14:46 UTC
Labels: bug
