### ISSUE TITLE
Play error for several resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#607] opened 2017-10-26 08:56 UTC
Examples:

- http://lobid.org/resources/HT019478435 ([JSON](http://lobid.org/resources/HT019478435.json))
- http://lobid.org/resources/HT019440462 ([JSON](http://lobid.org/resources/HT019440462.json))
- http://lobid.org/resources/HT019478435 ([JSON](http://lobid.org/resources/HT019478435.json))

I coudn't directly find the reason for this.

**Comment by acka47** [comment] 2017-10-26 09:16
Here are two more:

http://lobid.org/resources/HT019438890
http://lobid.org/resources/HT019338868

All of them have "Herausgeber/in" but on the other hand there are resources with "Herausgeber/in" that work, e.g. http://lobid.org/resources/HT019339215

**Comment by fsteeg** [comment] 2017-10-26 09:38
Fixed on stage:

http://stage.lobid.org/resources/HT019478435
http://stage.lobid.org/resources/HT019440462
http://stage.lobid.org/resources/HT019438890
http://stage.lobid.org/resources/HT019338868

The issue was caused by agents without IDs.

**Comment by acka47** [comment] 2017-10-26 09:40
+1

**Closed** 2017-10-26 09:44 UTC
Labels: bug, review
