### ISSUE TITLE
Remove lobid-Twitter Link

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1859] opened 2023-08-04 07:54 UTC

**Comment by acka47** [comment] 2023-08-04 08:06
Duplicate of https://github.com/hbz/lobid/issues/483, isn't it?

**Comment by dr0i** [comment] 2023-11-13 15:17
It's not a duplicate since this must be done in this repo. It's very similar, though.

**Comment by dr0i** [comment] 2023-11-16 16:23
Done, closing.

**Closed by dr0i** 2023-11-16 16:23 UTC
